sonar.organization=arcn-2026-1
sonar.projectKey=ARCN-2026-1_customer-services
sonar.projectName=customer-services
sonar.sources=.
# sonar.tests=test
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/.git/**,**/.github/**,**/docs/**,**/.venv/**,**/__pycache__/**
# sonar.test.inclusions=**/test/**,**/*test*.py
# sonar.python.coverage.reportPaths=coverage.xml
